### ISSUE TITLE
[BUG] a bytes-like object is required

### ISSUE THREAD

**Issue by Remi-Gau** [datalad/datalad-osf#123] opened 2020-08-01 05:27 UTC
Tried started playing with this. osf-credentials worked fine.

But I could not create a sibling.
```
~/test$ datalad create-sibling-osf --title test -s test-on-OSF
[ERROR  ] a bytes-like object is required, not 'list' [ciphers.py:update_into:140] (TypeError)
```

After that trying to reset credentials gives something similar.
```
:~$ datalad osf-credentials --reset
[WARNING] Failed to query keyring: a bytes-like object is required, not 'list' [ciphers.py:update_into:140] 
[ERROR  ] a bytes-like object is required, not 'list' [ciphers.py:update_into:140] (TypeError) 
```

Google threw this at me.
https://neurostars.org/t/datalad-difficulty-creating-github-sibling/4394/3

So here is what WTF gives me
```
~$ datalad wtf -S system -S dependencies
# WTF
## dependencies 
  - annexremote: 1.4.3
  - appdirs: 1.4.3
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 7.20190819+git2-g908476a9b-1~ndall+1
  - cmd:bundled-git: 2.20.1
  - cmd:git: 2.20.1
  - cmd:system-git: 2.24.0
  - cmd:system-ssh: 7.6p1
  - humanize: 2.5.0
  - iso8601: 0.1.12
  - keyring: 17.0.0
  - keyrings.alt: 3.4.0
  - msgpack: 0.5.6
  - requests: 2.22.0
  - wrapt: 1.10.11
## system 
  - distribution: debian/buster/sid
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 266
  - name: Linux
  - release: 5.4.0-42-generic
  - type: posix
  - version: #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020
```

**Additional context**

Not sure if it helps but I think my datalad install might not be the cleanest and might be a joyful mix of `apt-get` and `pip install`. :-)

**Comment by yarikoptic** [comment] 2020-08-01 05:32
If you run with --dbg, you would get into pdb session and can check full traceback etc

**Comment by adswa** [comment] 2020-08-03 05:56
Its a shot in the dark, but could you run ``pip freeze | grep SecretStorage`` and check whether it is version 3.1.1 or higher? 
I can reproduce your error message when I forcefully set back SecretStorage to version 3.1.0. If that's indeed the case, please run ``pip install -U SecretStorage`` to upgrade to the latest version (3.1.2; [the fix was released with 3.1.1](https://github.com/mitya57/secretstorage/pull/17)). The problem is that the ``keyring`` package specifies its dependency to ``SecretStorage`` with ``>=3``, and versions below 3.1.1 imploded when empty passwords were set (which is the case, I believe, with token authentication).

**Comment by adswa** [comment] 2020-08-03 06:11
ah, and your ``keyring`` version seems to be quite old (Nov. 2018). Maybe upgrade this first (also via ``pip install -U keyring``). 
BTW: Are you in a virtual environment? If not, please create one prior to this. I would feel really bad if this breaks things for any other software you may be running :smile:

**Comment by Remi-Gau** [comment] 2020-08-03 07:55
> ah, and your `keyring` version seems to be quite old (Nov. 2018). Maybe upgrade this first (also via `pip install -U keyring`).

Thanks.

OK will try all that.

> BTW: Are you in a virtual environment? If not, please create one prior to this. I would feel really bad if this breaks things for any other software you may be running smile

Well most of my coding diet is made of fast food (AKA matlab) (which explains why I did not grok @yarikoptic reply which I suspect was refering to using the python API, no?) so I unfortunately do not use virt env because there is so little to break.

Most of my current python ecosystem must look like a Jurassic Park once the power grid went offline. 

But I use virt env is on my list to Santa... Along with my sempiternal wish to switch to python.

**Comment by adswa** [comment] 2020-08-03 09:31
> I unfortunately do not use virt env because there is so little to break.

hihi, that's privilege and a pity at the same time! ;-) 
But for future reference, its about 3 lines of code. It requires ``virtualenv`` (you can get this via ``apt/apt-get`` (``sudo apt-get install virtualenv ``)). Creation and use is super fast:

```
# create a new virtual environment in ~/env/dl-osf (<path>/<name>)
$ virtualenv --python=python3 ~/env/dl-osf
# activate the new environment
$ . ~/env/dl-osf/bin/activate
# install any packages into the virtualenvironment
$ pip install datalad-osf.
```

You can activate a virtual env with either ``. ~/env/<name>/bin/activate`` or ``source ~/env/<name>/bin/activate``, and get out of it with ``deactivate``.

> I did not grok @yarikoptic reply which I suspect was refering to using the python API, no?)

What Yarik meant was adding the ``--dbg`` flag after ``datalad`` to any of your commands, as in 
```datalad --dbg osf-credentials --reset```
or 
```datalad --dbg create-sibling-osf --title test -s test-on-OSF```.

With this flag, DataLad executes your command, but if it encounters an error it throws you into an interactive Python session in the middle of the code where the error happened. In that session, you can explore in depth what is happening, and for example check the value of variables (a bit of it and pointer to how to use a debugger is detailed [here](http://handbook.datalad.org/en/latest/basics/101-135-help.html#debugging-like-a-datalad-developer)).
From the output you pasted it isn't possible to find out what exactly is going on unless we by chance have seen this type of error before (we haven't in this extension, as far as I know).
If I would be on your computer and would follow Yarik's advice, I would run ``datalad --dbg osf-credentials --reset``. Once I'm thrown into the debugger, I'd check with ``dir()`` which variables are currently defined, and print the value of each variable with ``p <varname>``. My hope would be to step through the code until I find out which variable is a list that should be a bytes-like-object, and with that get some insights on would have been supplied instead or where the error comes from exactly.

**Comment by Remi-Gau** [comment] 2020-08-05 09:22
hey @adswa 

Thanks for taking the time to explain this. Much appreciated!

OK so things worked in a virtual environment set up like you mentioned. :smile: 
I could create a sibling on OSF. (Not a sentence I expected saying this morning.)

Will try to update my dependencies to see if it fixes things.

One thing though: it seems datalad-osf created a sibling on the US servers of OSF. Is that the default behavior? If so I think that the GDPR gods will get annoyed for those cases where data is not supposed to be stored in places outside of Europe.

Might be better to set the storage location as "Germany Frankfurt" by default, no? (LMK if I should open an issue about this).

**Comment by adswa** [comment] 2020-08-05 11:01
> OK so things worked in a virtual environment set up like you mentioned.

:tada:

@yarikoptic, is there anything from our side that we can do to prevent this from happening to others? Specify an explicit dependency of ``keyring>=20.0.0``, for example?

> One thing though: it seems datalad-osf created a sibling on the US servers of OSF. Is that the default behavior? If so I think that the GDPR gods will get annoyed for those cases where data is not supposed to be stored in places outside of Europe.
Might be better to set the storage location as "Germany Frankfurt" by default, no? (LMK if I should open an issue about this).

Yes, very true. A new issue on this would be good.  it would definitely be very useful and important to have this feature. @bpoldrack and @mih know more about this, but I vaguely remember that the OSF's developer documentation did not really want to reveal how the default storage location is exposed in the API...

**Comment by adswa** [comment] 2022-03-02 14:18
The fix finally made it into datalad core with https://github.com/datalad/datalad/pull/6515

**Closed by adswa** 2022-03-02 14:18 UTC
Labels: bug
